Company page
bandlauz/bandla-frontend pull request #118
Opened 2024-04-10 18:24 UTC by akbarjorayev

Create company page

2024-04-12 13:03 UTC, nazarovctrl requested changes
Kalla qoyibsanu updatePhoto ni ichini yaxshilab qara keremas kodi copy paste qigansan

2024-04-12 13:56 UTC, akbarjorayev commented on src/pages/Company.js
> +  const updatePhoto = async (photoUrl, successMessage, errorMessage) => {
Got it

2024-04-12 13:57 UTC, akbarjorayev commented on src/pages/Company.js
> +  const updatePhoto = async (photoUrl, successMessage, errorMessage) => {
API ni ishlatib korsatib ber bro

2024-04-17 12:30 UTC, nazarovctrl requested changes

2024-04-17 12:30 UTC, nazarovctrl commented on src/components/Input.js
> +import React, { useEffect, useRef, useState } from 'react';
nega alohida Input ishlatvosan, tayyori yogmi?  Bu Input  Profile formasidagi inputdan qanaqa afzalligi bor

2024-04-17 12:30 UTC, nazarovctrl commented on src/pages/App.js
>  import WrongPath from './WrongPath';
wrongPath importiniyam oxiriga qoyvor

2024-04-17 12:30 UTC, nazarovctrl commented on src/pages/Company.js
> +import { toast } from 'react-toastify';
nimabu nogironmi ajratib qoyibsan😂

2024-04-17 12:30 UTC, nazarovctrl commented on src/pages/Company.js
> +  const FINDURL =
nega kere bu?

2024-04-17 13:09 UTC, akbarjorayev commented on src/components/Input.js
> +import React, { useEffect, useRef, useState } from 'react';
Bu input ni san xohlaganindaqa style qoyolisan

2024-04-17 13:09 UTC, akbarjorayev commented on src/pages/App.js
>  import WrongPath from './WrongPath';
ok

2024-04-17 13:10 UTC, akbarjorayev commented on src/pages/Company.js
> +import { toast } from 'react-toastify';
man emas, bu code ni man copy paste qilganamn

2024-04-17 13:10 UTC, akbarjorayev commented on src/pages/Company.js
> +  const FINDURL =
nima FINDURL ni, agar shu bosa ketb qolbdi. keremas

2024-04-17 13:34 UTC, nazarovctrl commented on src/pages/Company.js
> +import { toast } from 'react-toastify';
Hop copy paste qilasanmi boshqa narsa qilasanmi bu codeni yozvotgan ozin shunga togrlab yoz

2024-04-18 11:02 UTC, nazarovctrl requested changes

2024-04-18 11:02 UTC, nazarovctrl commented on src/pages/Company.js
> +import { toast } from 'react-toastify';
togrilanmagan!

2024-04-18 11:02 UTC, nazarovctrl commented on src/pages/Company.js
> +  const FINDURL =
togrilanmagan!

2024-04-18 11:02 UTC, nazarovctrl commented on src/pages/Company.js
> +    const something = await Request(
try catch qani?

2024-04-18 12:52 UTC, nazarovctrl requested changes

2024-04-18 12:52 UTC, nazarovctrl commented on src/pages/App.js
>  import WrongPath from './WrongPath';
eng oxirigia qoyish keredi, company ni pasigamas

2024-04-24 09:31 UTC, akbarjorayev commented
Show **Status**!

2024-04-26 16:22 UTC, nazarovctrl requested changes

2024-04-26 16:22 UTC, nazarovctrl commented on src/components/Input.js
> +
nega kere bu bosh qator? ochirib tasha

2024-04-26 16:22 UTC, nazarovctrl commented on src/components/Navbar.js
> +    if (typeof path === 'string') window.location.href = path;
nega if kere?  o'zi bu handleClose ga faqat string  kevotganini usizam bilib turibsanu

2024-04-26 16:22 UTC, nazarovctrl commented on src/pages/Company.js
> +        setPhotoUrl(response.data.data.photoUrl);
bu logika setCompany() ichida boladigan qilish kere

2024-04-26 16:22 UTC, nazarovctrl commented on src/pages/Company.js
> +
response dagi danniy ishlatilmagan! for more information -> telegram chat

2024-05-01 11:35 UTC, akbarjorayev reviewed
Review this @nazarovctrl PLS

2024-05-02 14:13 UTC, nazarovctrl requested changes

2024-05-02 14:13 UTC, nazarovctrl commented on src/pages/Company.js
> +          {company?.data?.data?.status && <button>Created</button>}
xato status qiymatini korsatish kerak. hozirgi code da status bolsa faqat Created korinadi

2024-05-02 14:13 UTC, nazarovctrl commented on src/pages/Company.js
> +      setCompany(response);
xato setCopmany ichiga faqat company malutmoalrini berish kere hozi resonse ichida request jonatishdagi har xil balo battar musr malumotla bor
```suggestion
      setCompany(response.data.data);
```

2024-05-02 14:13 UTC, nazarovctrl commented on src/pages/Company.js
> +      setCompany(response);
xato file-store api dan company ga oid malumto kemidi lekin setCompany qilinvoti, 
Yechim:
company ichidagi url ni response.data.data.url ga tenglab qoyish kerak
company.url = response.data.data.url

2024-05-02 14:13 UTC, nazarovctrl commented on src/pages/Company.js
> +        setCompany(response);
```suggestion
        setCompany(response.data.data);
```

2024-05-02 14:13 UTC, akbarjorayev reviewed
Status **fixed** @nazarovctrl

2024-05-02 17:16 UTC, akbarjorayev reviewed
I think **All** comments were **resolved**! @nazarovctrl

2024-05-02 17:21 UTC, nazarovctrl submitted a review, later dismissed

2024-05-02 17:21 UTC, nazarovctrl commented on src/pages/Company.js
> +        <div className="inputs">
Inputlarni  disabled bolishini yaxshilash kerak

2024-05-02 17:42 UTC, akbarjorayev commented on src/pages/Company.js
> +        <div className="inputs">
Qilomoman manmcha

2024-05-04 01:31 UTC, akbarjorayev reviewed
Good! But 2 Inputs!

2024-05-04 01:31 UTC, akbarjorayev commented on src/pages/Company.js
> +          {!company?.id && (
They actually **work** @nazarovctrl

2024-05-04 09:51 UTC, akbarjorayev commented on src/pages/Company.js
> +        <div className="inputs">
boldi @nazarovctrl

2024-05-05 11:31 UTC, akbarjorayev reviewed
Good 👍

2024-05-05 16:30 UTC, nazarovctrl approved these changes
LGTM

2024-05-05 16:30 UTC, merged