Avatar Letter
bandlauz/bandla-frontend pull request #139
Opened 2024-05-10 17:15 UTC by akbarjorayev

2024-05-10 17:16 UTC, akbarjorayev reviewed
**LGTM**

2024-05-10 17:58 UTC, nazarovctrl requested changes

2024-05-10 17:58 UTC, nazarovctrl commented on src/components/Navbar.js
> +                      {avatarLtr}
Agar user royxatdan o'tgan bosa lekin hali ismi qoyilmagan bosa Nima hard korinadi?

2024-05-11 00:16 UTC, akbarjorayev commented on src/components/Navbar.js
> +                      {avatarLtr}
B

2024-05-11 14:50 UTC, nazarovctrl approved these changes
LGTM

2024-05-11 14:50 UTC, merged