Created alert
bandlauz/bandla-frontend pull request #92
Opened 2024-03-03 06:40 UTC by akbarjorayev

2024-03-03 06:46 UTC, nazarovctrl requested changes

2024-03-03 06:46 UTC, nazarovctrl commented on src/components/Alert.js
> -import React from 'react';
; nega buni ob tashadin?

2024-03-03 06:46 UTC, nazarovctrl commented on src/components/Alert.js
> -export default Alert;
; ?

2024-03-03 06:46 UTC, nazarovctrl commented on src/pages/Profile.js
> +        setShowAlertPic(false)
;  qani

2024-03-03 06:52 UTC, akbarjorayev commented
boldi qoshldi

2024-03-06 12:29 UTC, akbarjorayev commented
Tayyor

2024-03-06 16:01 UTC, nazarovctrl requested changes

2024-03-06 16:01 UTC, nazarovctrl commented on src/components/Navbar.js
>  import NavbarSimple from "../components/NavbarSimple"
shu import bilan pasidagi importgayam ;

2024-03-06 16:01 UTC, nazarovctrl commented on src/pages/Profile.js
>  import "./css/Profile.css"
bu joyda yam ; hammasiga

2024-03-06 16:01 UTC, nazarovctrl commented on src/util/Image.js
> +function getData(img) {
;

2024-03-10 05:59 UTC, merged